import {
  Activity,
  BookOpen,
  Brain,
  Briefcase,
  Car,
  Clock,
  Code,
  Coffee,
  Dumbbell,
  FlaskConical,
  FolderHeart,
  Heart,
  Home,
  Laptop,
  Lightbulb,
  MessageCircle,
  Music,
  Palette,
  Phone,
  Plane,
  Rocket,
  Save,
  Scissors,
  Settings,
  ShoppingBag,
  Sparkles,
  Star,
  Sun,
  Target,
  ThumbsUp,
  Timer,
  Train,
  Trophy,
  Utensils,
  Wallet,
  Watch,
  Wheat,
  Wifi,
  Wrench,
  Zap,
} from 'lucide-react';

export const ICONS = {
  activity: Activity,
  'book-open': BookOpen,
  brain: Brain,
  briefcase: Briefcase,
  car: Car,
  clock: Clock,
  code: Code,
  coffee: Coffee,
  dumbbell: Dumbbell,
  flask: FlaskConical,
  'folder-heart': FolderHeart,
  heart: Heart,
  home: Home,
  laptop: Laptop,
  lightbulb: Lightbulb,
  message: MessageCircle,
  music: Music,
  palette: Palette,
  phone: Phone,
  plane: Plane,
  rocket: Rocket,
  save: Save,
  scissors: Scissors,
  settings: Settings,
  'shopping-bag': ShoppingBag,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  target: Target,
  thumbsup: ThumbsUp,
  timer: Timer,
  train: Train,
  trophy: Trophy,
  utensils: Utensils,
  wallet: Wallet,
  watch: Watch,
  wheat: Wheat,
  wifi: Wifi,
  wrench: Wrench,
  zap: Zap,
} as const;

export type IconKey = keyof typeof ICONS;

export const ICON_NAMES = Object.keys(ICONS) as IconKey[];

export const getIcon = (key: string) => {
  return ICONS[key as IconKey] || Star;
};